name: Repo syncer
on:
  schedule:
    - cron: "*/60 * * * *"
jobs:
  sync_plz_thx:
    name: Sync and push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'        # fetch all history
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: ./actions/syncer/
      uses: ./actions/syncer/
