name: Extension uploader
on:
  push:
    branches:
      - master
jobs:
  upload_plz_thx:
    name: Uploader
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ./actions/uploader/
      uses: ./actions/uploader/
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
